/// Flutter icons AnchorPoint
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AnchorPoint
///      fonts:
///       - asset: fonts/AnchorPoint.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AnchorPointIcons {
  AnchorPointIcons._();

  static const _kFontFam = 'AnchorPoint';
  static const String? _kFontPkg = null;

  static const IconData anchor_point_icon = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData anchor_point_step1 = IconData(
    0xe801,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData anchor_point_step3 = IconData(
    0xe802,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData anchor_point_step2 = IconData(
    0xe803,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
